//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechniqueStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketUser
    {
        public int id_basket { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_itemcategory { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual Users Users { get; set; }
    }
}
