//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechniqueStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemCategory()
        {
            this.BasketUser = new HashSet<BasketUser>();
            this.OrderItems = new HashSet<OrderItems>();
            this.Properties = new HashSet<Properties>();
        }
    
        public int id_itemCategory { get; set; }
        public Nullable<int> id_category { get; set; }
        public string nameItem { get; set; }
        public string img_url { get; set; }
        public Nullable<int> instock_id { get; set; }
        public Nullable<int> CountINWarehouse { get; set; }
        public Nullable<int> price { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketUser> BasketUser { get; set; }
        public virtual CategoryTech CategoryTech { get; set; }
        public virtual InStock InStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Properties> Properties { get; set; }
    }
}
