//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechniqueStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int id_orderItems { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual Order Order { get; set; }
    }
}
