//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechniqueStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public int id_properties { get; set; }
        public Nullable<int> id_propname { get; set; }
        public string ValueProp { get; set; }
        public Nullable<int> id_item { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual PropertyName PropertyName { get; set; }
    }
}
